<a href="https://colab.research.google.com/github/jaeduck223/jaeduck223/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%88%98%EC%97%85%EC%8B%9C%EA%B0%84_%EC%8B%A4%EC%8A%B5(1%EC%A3%BC%EC%B0%A8_2%EA%B0%95).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

obj = pd.Series([4,7,-5,3])
#왼쪽에 색인, 오른쪽에 해당색인의  값을 나타낸다.
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.values #value 속성

array([ 4,  7, -5,  3])

In [ ]:
obj.index #index 속성

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c']) #각각의 데이터를 지칭하는 색인을 지정하여 생성
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
obj2.values

array([ 4,  7, -5,  3])

In [ ]:
obj2['a']

-5

In [ ]:
obj2['d'] = 6
obj2[['c','a','d']]  #obj2['c','a','d']  : 에러발생

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
import numpy as np

np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [ ]:
'b' in obj2

True

In [ ]:
'e' in obj2

False

In [ ]:
sdata = {'Ohio': 35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000} #Python Dictionary
obj3 = pd.Series(sdata) #Dictionary 객체로부터 Series 객체 생성
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj3.to_dict() # Series to dictionary

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [ ]:
states = ['California','Ohio','Oregon','Texas'] #색인을 직접 지정
obj4 = pd.Series(sdata, index=states)
obj4
#California에 대한값은 없으므로 NaN(Not a Number)으로 표시되고 누락된(NA) 값으로 취급
#Utha는 states에 없으므로 실행결과에서는 빠지게 된다.

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
pd.isnull(obj4) #누락된(NA)값을 찾는 메소드, pandas의 메소드

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notnull(obj4) #누락된(NA)값을 찾는 메소드(isnull과 반대로), pandas의 메소드

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj4.isnull()  #Series의 인스턴스 메소드로도 가능

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj4.notnull()  #Series의 인스턴스 메소드로도 가능

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
obj4.name = 'population'  #Series 객체에 name 속성부여
obj4.index.name = 'state' #Series 색인에 name 속성부여

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:
obj = pd.Series([4,7,-5,3]) #name 속성이 없는 경우 : 위 결과와 비교
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.index = ['Bob','Steve','Jeff','Ryan'] #색인은 대입하여 변경 할 수도 있다.
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year' : [2000, 2001, 2002, 2001, 2002, 2003],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
# 만들어진 DataFrame의 색인은 Series와 같은 방식으로 대입되며 컬럼은 정렬되어 저장된다.

In [ ]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
frame.head() #frame.tail()
# 큰 DataFrame을 다룰 때는 hesd 메소드를 사용하여 처음 5개의 row만 출력할 수도 있다.

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [ ]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
pd.DataFrame(data, columns=['year', 'state','pop'])
#원하는 순서대로 column을 지정하면 원하는 순서를 가진 DataFrame을 생성한다.

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
pd.DataFrame(data, columns=['year', 'state'])
#원하는 순서대로 column을 지정하면 원하는 순서를 가진 DataFrame을 생성한다.

   year   state
0  2000    Ohio
1  2001    Ohio
2  2002    Ohio
3  2001  Nevada
4  2002  Nevada
5  2003  Nevada

In [ ]:
pd.DataFrame(data, columns=['year'])

   year
0  2000
1  2001
2  2002
3  2001
4  2002
5  2003

In [ ]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [ ]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2
# Series와 마찬가지로 Dictionary에 없는 값을 넘겨주면 NaN으로 처리된다.

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2['state']
# DataFrame의 컬럼은 Seriese처럼 사전형식의 표기법으로 접근하거나또는 frame2.state 처럼 속성형식으로 접근
#frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2[['state', 'pop']]

        state  pop
one      Ohio  1.5
two      Ohio  1.7
three    Ohio  3.6
four   Nevada  2.4
five   Nevada  2.9
six    Nevada  3.2

In [ ]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
frame2["state"] # 이중 따옴표를 써서 해도 똑같이 출려됨.

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2.loc['three']  #frame2.loc[['two', 'three']] : 이 경우 출력은 DataFrame이 된다

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
frame2.iloc[2] # 정상동작, iloc : row에 해당하는 정수값을 가지는 순서 지정

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
frame2.loc[['two', 'three']] #loc는 반드시 문자열을 대입!

       year state  pop debt
two    2001  Ohio  1.7  NaN
three  2002  Ohio  3.6  NaN

In [ ]:
frame2.iloc[2] # 정상동작, iloc : row에 해당하는 정수값을 가지는 순서 지정 -> 숫자에 해당하는 값을 출력함.

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
frame2['year']
#frame2[['year', 'pop']]

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
frame2['eastern'] = frame2.state == 'Ohio' # state 컬럼의 값이 'Ohio'인지 아닌지에 대한 불리언 값을 갖는 새로운 컬럼 생성
frame2

       year   state  pop debt  eastern
one    2000    Ohio  1.5  NaN     True
two    2001    Ohio  1.7  NaN     True
three  2002    Ohio  3.6  NaN     True
four   2001  Nevada  2.4  NaN    False
five   2002  Nevada  2.9  NaN    False
six    2003  Nevada  3.2  NaN    False

In [ ]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [ ]:
#중첩된 dictionary를 이용하여 데이터를 생성할 수있다.
# 중첩된 dictionary를 DataFrame에 넘기면, 바깥의 키는 컬럼이 되고 안쪽의 키는 로우가 된다.
pop = {'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
       'Nevada': {2001: 2.4, 2002: 2.9}}

frame3 = pd.DataFrame(pop)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
#Numpy 배열과 유사한 문법으로 데이터를 전치(transpose)할 수 있다.
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [ ]:
pop

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}  #frame3['Nevada'][:-1]과 같은 결과
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [ ]:
#name 속성 지정
frame3.index.name = 'year'
frame3.columns.name = 'state'

frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [ ]:
frame2.values  #DataFrame의 컬럼이 서로 다른 dtype을 가지고 있다면 모든 컬럼을 수용하기 위해 그 컬럼 배열의 dtype이 선택된다.
#frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [ ]:
import pandas as pd
import numpy as np

obj = pd.Series(range(3), index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [ ]:
#자료구조 사이에서 안전하게 공유될 수 있다.
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
obj2.index is labels

True

In [ ]:
frame3.index

Index([2000, 2001, 2002], dtype='int64', name='year')

In [ ]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [ ]:
'Ohio' in frame3.columns

True

In [ ]:
2003 in frame3.columns

False

In [ ]:
#파이썬의 집합과 갈리 pandas의 인덱스는 중복되는 값을 허용한다.
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [ ]:
import pandas as pd
obj=pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [ ]:
#위의 Series객체에 reindex를 호출하면 새로운 색인에 맞게 재배열하고, 존재하지 않는 색인값이 있다면 NaN을 추가한다.
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
#시계열 같은 순차적 데이터를 재색인할때 값을 보간하거나 채워넣을경우가 있다.
#method 옵션을 사용해서 이를 해결할수 있으며, ffill 같은 매서드를 사용해서 누락된값을 직전의 값으로 채울 수 있다.
obj3.reindex(range(6), method='ffill')  #bfil과 비교
#obj3.reindex(range(6), method='bfill')  #bfil과 비교

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [ ]:
import numpy as np
#DataFrame에 대한 reindex는 row, col 둘다 변경 가능하다.
frame = pd.DataFrame(np.arange(9).reshape(3,3),
                     index=['a','c','d'], columns=['Ohio', 'Texas', 'California'])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2=frame.reindex(['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [ ]:
#컬럼은 columns 예약어를 사용해서 재색인한다.
states=['Texas', 'Utha', 'California']
frame.reindex(columns=states)
# frame.reindex(states, axis="columns")  #같은 결과를 다른방법으로...

   Texas  Utha  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [ ]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

In [ ]:
frame.loc[["a", "d", "c"], ["California", "Texas"]] #iloc로 바꾸는 거 해보자!!!!

   California  Texas
a           2      1
d           8      7
c           5      4

In [ ]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
del obj['a']

In [ ]:
obj

b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
new_obj = obj.drop('c')  # del obj['c']  #예약어 del을 사용해도 됨
new_obj

b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj.drop(['d','c'])

b    1.0
e    4.0
dtype: float64